spring:
    application:
      name: gateway-service

server:
  port: 10003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  register-with-eureka: false
instance:
  preferIpAddress: true

